name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'

jobs:
  spelling:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/setup.py', 'doc/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install enchant hunspell aspell-en
      - name: Install Dependencies
        run: python -m pip install -Ur doc/requirements.txt
      - name: Spellcheck docs
        run: make spelling
        working-directory: ./doc
      - name:
        run: '[ ! -s _build/spelling/output.txt ]'
        working-directory: ./doc

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/setup.py', 'doc/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip3 install -Ur doc/requirements.txt
      - name: Linkcheck docs
        run: make linkcheck
        working-directory: ./doc
