name: Code Style

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'src/pretalx/locale/**'
      - 'src/pretalx/static/**'
      - 'doc/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'src/pretalx/locale/**'
      - 'src/pretalx/static/**'
      - 'doc/**'

jobs:
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip3 install -Ue "src[dev]"
      - name: Run isort
        run: isort -c .
        working-directory: ./src
  flake:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip3 install -Ue "src[dev]"
      - name: Run flake8
        run: flake8 .
        working-directory: ./src
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip3 install -Ue "src[dev]"
      - name: Run black
        run: black --check .
        working-directory: ./src
  docformatter:
    name: docformatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip3 install -Ue "src[dev]"
      - name: Run docformatter
        run: docformatter --check -r .
        working-directory: ./src
  djhtml:
    name: djhtml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip3 install -Ue "src[dev]"
      - name: Run djhtml
        run: 'find -name "*.html" | xargs djhtml -c'
        working-directory: ./src
  packaging:
    name: packaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip3 install twine -Ue "src[dev]"
      - name: Run check-manifest
        run: check-manifest .
        working-directory: ./src
      - name: Build package
        run: python setup.py sdist
        working-directory: ./src
      - name: Check package
        run: twine check dist/*
        working-directory: ./src
